name: FTP Deploy

on:
  push:
    branches:
      - main  # Oder dein gewünschter Branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install FTP Deployment Tool
      run: sudo apt-get install lftp

    - name: Deploy to FTP server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
      run: |
        lftp -f "
        open $FTP_HOST
        user $FTP_USERNAME $FTP_PASSWORD
        mirror -R --delete ./ $FTP_REMOTE_DIR
        bye
        "
